DROP DATABASE IF EXISTS AjaxChaos;

CREATE DATABASE AjaxChaos;

USE AjaxChaos;

CREATE TABLE Compliment(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	Text VARCHAR(100) NOT NULL,
    InsertionPoint INT NULL
);

CREATE TABLE Color(
	Primary Key(Name, HexCode),
	Name VARCHAR(30) NOT NULL,
    HexCode VARCHAR(6) NOT NULL
);

CREATE TABLE Animal(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	Name VARCHAR(50) NOT NULL,
    Kingdom VARCHAR(50) NULL,
    Phylum VARCHAR(50) NULL,
	Class VARCHAR(50) NULL,
	`Order` VARCHAR(50) NULL,
	SuperFamily VARCHAR(50) NULL,
	Family VARCHAR(50) NULL
);